version: "3.9"

volumes:
  suricatalogs:
  zeeklogs:

services:
  mgmt:
    image: wernight/ngrok
    network_mode: host
    environment:
      - NGROK_PORT=2375
      - NGROK_AUTH=${ngrok_key}
    profiles:
      - mgmt

  eset:
    build:
      context: ./eset
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: eset_sentinel
    ports:
      - "2514:514"
    profiles:
      - eset

  trend:
    build:
      context: ./trend
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: trend_sentinel
    ports:
      - "3514:514/udp"
    profiles:
      - trend

  netflow:
    build:
      context: ./netflow
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: netflow_sentinel
    ports:
      - "2055:2055/udp"
    profiles:
      - netflow

  fortigate:
    build:
      context: ./fortigate
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: fortigate_sentinel
    ports:
      - "0.0.0.0:514:514"
    profiles:
      - fortigate

  sonicwall:
    build:
      context: ./sonicwall
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: sonicwall_sentinel
    ports:
      - "0.0.0.0:514:514"
      - "0.0.0.0:514:514/udp"
    profiles:
      - sonicwall

  cloudhive:
    build:
      context: ./cloudhive
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: cloudhive_sentinel
    ports:
      - "0.0.0.0:515:514"
      - "0.0.0.0:515:514/udp"
    profiles:
      - cloudhive
  opnsense:
    build:
      context: ./opnsense
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: opnsense_sentinel
    ports:
      - "0.0.0.0:514:514"
      - "0.0.0.0:514:514/udp"
    profiles:
      - opnsense


  ciscoasa:
    build:
      context: ./ciscoasa
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: ciscoasa_sentinel
    ports:
      - "0.0.0.0:514:514"
      - "0.0.0.0:514:514/udp"
    profiles:
      - ciscoasa

  juniper:
    build:
      context: ./juniper
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: juniper_sentinel
    ports:
      - "0.0.0.0:514:514"
      - "0.0.0.0:514:514/udp"
    profiles:
      - juniper


  thycotic:
    build:
      context: ./thycotic
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: thycotic_sentinel
    ports:
      - "0.0.0.0:514:514"
    profiles:
      - thycotic
      
  passwordstate:
    build:
      context: ./passwordstate
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: passwordstate_sentinel
    ports:
      - "0.0.0.0:4514:514"
    profiles:
      - passwordstate
  zeek:
    build:
      context: ./zeek
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: zeek_sentinel
    volumes:
      - type: volume
        source: zeeklogs
        target: /logs/
    profiles:
      - ids

  suricata:
    build:
      context: ./suricata
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: suricata_sentinel
    environment:
      - LS_JAVA_OPTS=-Xmx4g
    volumes:
      - type: volume
        source: suricatalogs
        target: /logs
    profiles:
      - ids

  suricata_ids:
    build:
      context: ./suricata_ids
    image: suricata_ids
    volumes:
      - type: volume
        source: suricatalogs
        target: /var/log/suricata
    network_mode: host
    environment:
      - SURICATA_OPTIONS=-c /suricata/suricata.yaml
    cap_add:
      - sys_nice
      - net_admin
    command: -i ${span_interface}
    profiles:
      - ids

  zeek_ids:
    build:
      context: ./zeek_ids
      args:
        span_interface: ${span_interface}
    image: zeek_ids
    volumes:
      - type: volume
        source: zeeklogs
        target: /opt/zeek/spool/zeek
    network_mode: host
    cap_add:
      - sys_nice
      - net_admin
    stdin_open: true # docker run -i
    tty: true # docker run -t
    profiles:
      - ids

  vmware_old:
    build:
      context: ./vmware
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: vmware_sentinel
    ports:
      - "0.0.0.0:1514:514/udp"
    profiles:
      - vmware_old

  sophosxg:
    build:
      context: ./sophosxg
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: sophosxg
    ports:
      - "0.0.0.0:5514:514"
      - "0.0.0.0:5514:514/udp"
    profiles:
      - sophos

  sophoscentral:
    build:
      context: ./sophoscentral
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: sophoscentral
    ports:
      - "0.0.0.0:6514:514/udp"
    profiles:
      - sophos

  sophoscentral_api:
    build:
      context: ./sophoscentral_api
      args:
        sophosAPIToken: ${sophosAPIToken}
        sophosAPIid: ${sophosAPIid}
        sophosAPIsecret: ${sophosAPIsecret}
        sophosAPItenant: ${sophosAPItenant}
    image: sophoscentral_api
    profiles:
      - sophos
      
  vmware:
    build:
      context: ./vmware
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
        syslog_forward: ${syslog_forward}
    image: vmware
    ports:
      - "0.0.0.0:514:514"
      - "0.0.0.0:514:514/udp"
    profiles:
      - vmware

  hytrust:
    build:
      context: ./hytrust
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: hytrust
    ports:
      - "0.0.0.0:7514:514"
    profiles:
      - hytrust

  windows_legacy:
    build:
      context: ./windows_legacy
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: windows_legacy
    ports:
      - "0.0.0.0:3514:514"
    profiles:
      - windows_legacy
    
  netscaler:
    build:
      context: ./netscaler
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: netscaler
    ports:
      - "0.0.0.0:1514:514"
    profiles:
      - netscaler
    
  radius:
    build:
      context: ./radius
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: radius
    ports:
      - "0.0.0.0:514:514"
    profiles:
      - radius

  darktrace:
    build:
      context: ./darktrace
      args:
        environment_name: ${environment_name}
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: darktrace
    ports:
      - "0.0.0.0:1514:514"
    profiles:
      - darktrace
        
  redirector:
    build:
      context: ./redirector
    image: redirector
    ports:
      - "0.0.0.0:514:514"
    profiles:
      - redirector
