version: "3.9"

volumes: 
  suricatalogs:
  zeeklogs:

services:
  eset:
    build:
      context: ./eset
      args:
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: eset_sentinel
    ports:
      - "2514:514"
    profiles:
      - eset

  trend:
    build:
      context: ./trend
      args:
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: trend_sentinel
    ports:
      - "3514:514"
    profiles:
      - trend

  netflow:
    build:
      context: ./netflow
      args:
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: netflow_sentinel
    ports:
      - "2055:2055"
    profiles:
      - netflow

  fortigate:
    build:
      context: ./fortigate
      args:
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: fortigate_sentinel
    ports:
      - "0.0.0.0:4514:514"
    profiles:
      - fortigate

  zeek:
    build:
      context: ./zeek
      args:
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: zeek_sentinel
    volumes:
      - type: volume
        source: zeeklogs
        target: /logs/
    profiles:
      - ids

  suricata:
    build:
      context: ./suricata
      args:
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: suricata_sentinel
    volumes:
      - type: volume
        source: suricatalogs
        target: /logs
    profiles:
      - ids

  suricata_ids:
    build:
      context: ./suricata_ids
    image: suricata_ids
    volumes:
      - type: volume
        source: suricatalogs
        target: /var/log/suricata
    network_mode: host
    cap_add:
      - sys_nice
      - net_admin 
    command: -i eth1
    profiles:
      - ids

  zeek_ids:
    build:
      context: ./zeek_ids
    image: zeek_ids
    volumes:
      - type: volume
        source: zeeklogs
        target: /opt/zeek/spool/zeek
    network_mode: host
    cap_add:
      - sys_nice
      - net_admin 
    profiles:
      - ids

  vmware:
    build:
      context: ./vmware
      args:
        workspaceID: ${workspaceID}
        workspaceKey: ${workspaceKey}
    image: vmware_sentinel
    ports:
      - "0.0.0.0:1514:514/udp"
    profiles:
      - vmware