services:
  fortigate:
    build:
      args:
        environment_name: ''
        table: fortigate
        workspaceID: ''
        workspaceKey: ''
      context: ./fortigate
      restart: always
    image: fortigate_sentinel
    ports:
    - 6514:514
  paloalto:
    build:
      args:
        environment_name: ''
        table: paloalto
        workspaceID: ''
        workspaceKey: ''
      context: ./paloalto
      restart: always
    image: paloalto_sentinel
    ports:
    - 9514:514/udp
