input {
  tcp {
    port => 514
    type => syslog
  }
  udp {
    port => 514
    type => syslog
  }
}

filter {
  if ("dummyvalue123" in [message]) {
    drop {
    }
  }
}

output {
  pipeline {
    send_to => ["sentinel"]
  }
}

